/**
 * cron/wrapper.ts — the generated script a fired local Entry executes: the one home for wrapper
 * generation (docs/research/comparables.md §6-1, source-dive.md A13).
 *
 * A bare command dies in the scheduler's bare environment: cron and launchd source no profile
 * (no PATH, no API keys), `%` is special in a crontab line, and output is lost to local mail. So
 * every local backend schedules a wrapper instead — `add` writes `<dir>/.loop/cron/<id>.sh`
 * (unix, 0755) or `<id>.cmd` (Windows), the scheduler entry invokes that, and both output streams
 * append to `<dir>/.loop/cron/<id>.log`. `remove` deletes the wrapper and keeps the log:
 * State-adjacent evidence, cheap to keep.
 *
 * The unix wrapper's `#!/bin/bash -l` login shell resolves PATH and API keys *by reference at
 * fire time* — the A13 rule: capture env references, never snapshot values — and a single-argument
 * shebang is portable across macOS and Linux. Windows scheduled tasks get the user's registry
 * environment instead: system- and user-level variables are present, profile-only ones are not.
 * The wrapper `cd`s into the project dir itself; the scheduler hands it nothing, it stands alone.
 *
 * The wrapper is also where every local backend enforces the Entry's lifetime (ADR 0016), because
 * it is the only code that runs at fire time. On a settled lifetime, `loop run` leaving with a
 * settled code — 0 (Goal met) or 2 (gave up), MVP §10's exit table — makes the wrapper run
 * `loop cron remove <id>` on itself (ADR 0013). The caps compose onto either lifetime: a
 * run-capped Entry counts its runs in `<dir>/.loop/cron/<id>.runs` (absent reads as 0), an
 * expiring one carries its deadline baked in as epoch seconds — the install stamp needs no side
 * file, and a tick past the deadline removes the Entry *instead of* running, because the caps
 * exist to bound cost. Deleting the running script is safe in both flavors: bash keeps its fd
 * open past the unlink, and cmd re-reads a batch file per line, so it simply stops at the deleted
 * file's end — which is why the remove is the wrapper's last act. (cmd gets its clock from
 * PowerShell; if that fails, NOW stays 0 and the tick runs — degrade toward running, never toward
 * a wrong removal.)
 *
 * The pure text/path builders are split from the one impure boundary ({@link systemWrapperFiles})
 * so the backends stay testable over in-memory files.
 */

import { chmodSync, mkdirSync, rmSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import type { Step } from "./backend.ts"
import type { Entry } from "./entry.ts"
import { durationSeconds } from "../../duration.ts"
import * as sh from "./sh.ts"

/**
 * The argv of this `loop` bin — the absolute runtime + CLI script, so it works under the
 * scheduler's bare PATH and reruns the same `loop` the user just invoked. The wrapper appends the
 * subcommand: `run` on fire, `cron remove <id>` on a settled exit.
 */
export function currentCli(): string[] {
  const runtime = process.execPath
  const script = process.argv[1]
  return script ? [runtime, resolve(script)] : [runtime]
}

/** An Entry's generated files live at `<dir>/.loop/cron/<id>.*`, in the flavor's own separators. */
const file = (dir: string, id: string, sep: string, ext: string) => [dir, ".loop", "cron", id + ext].join(sep)

/** Where an Entry's wrapper lives: `<dir>/.loop/cron/<id>.sh` (unix) or `…\<id>.cmd` (Windows). */
export function wrapperPath(dir: string, id: string, flavor: "sh" | "cmd"): string {
  return file(dir, id, flavor === "sh" ? "/" : "\\", "." + flavor)
}

/** Where a run-capped Entry counts its runs: `<dir>/.loop/cron/<id>.runs`; absent reads as 0. */
export function runsPath(dir: string, id: string, flavor: "sh" | "cmd"): string {
  return file(dir, id, flavor === "sh" ? "/" : "\\", ".runs")
}

/**
 * The bash wrapper a unix Entry (crontab, launchd) executes; its shebang carries the login shell.
 * `installedAt` (epoch seconds) is the install stamp an expiry counts from. The body composes by
 * the lifetime's features: an expiry guard, run counting, and the self-removal conditions —
 * settled exits only on a settled lifetime, the run cap wherever `maxRuns` is set.
 */
export function shWrapper(entry: Pick<Entry, "id" | "dir" | "until">, cli: string[], installedAt: number): string {
  const { id, dir, until } = entry
  const log = file(dir, id, "/", ".log")
  const argv = (sub: string[]) => [...cli, ...sub].map(sh.quote).join(" ")
  const run = `${argv(["run"])} >> ${sh.quote(log)} 2>&1`
  const remove = `${argv(["cron", "remove", id])} >> ${sh.quote(log)} 2>&1`
  const head = `#!/bin/bash -l
# generated by loop.js — \`loop cron add\`; regenerated on add, deleted on remove.
# -l: a login shell resolves PATH and API keys by reference at fire time — cron and launchd
# source no profile of their own.
cd ${sh.quote(dir)} || exit 1
`
  const guard =
    until.expires === undefined
      ? ""
      : `# Expires ${until.expires} after install. The cap bounds cost, so a tick past the deadline
# removes the Entry instead of running.
if [ "$(date +%s)" -ge ${installedAt + durationSeconds(until.expires)} ]; then
  ${remove}
  exit 0
fi
`
  if (!until.settled && until.maxRuns === undefined) return head + guard + `exec ${run}\n`
  const runs = sh.quote(runsPath(dir, id, "sh"))
  const count =
    until.maxRuns === undefined
      ? ""
      : `runs=$(( $(cat ${runs} 2>/dev/null || echo 0) + 1 ))
echo "$runs" > ${runs}
`
  const why = until.settled
    ? `# 0 = settled ok, 2 = settled give-up (MVP §10's exit table) — or run ${until.maxRuns}, the cap:
# this Entry's job is done — it removes itself. Any other exit before the cap is an interruption;
# the next tick resumes it.`
    : `# Run ${until.maxRuns} is the cap: this Entry ends here. A settled exit alone never removes a
# forever Entry — each tick re-judges through the Verify gate; the cap is its only self-removal.`
  const gone = [
    ...(until.settled ? ["[ $rc -eq 0 ] || [ $rc -eq 2 ]"] : []),
    ...(until.maxRuns === undefined ? [] : [`[ "$runs" -ge ${until.maxRuns} ]`]),
  ].join(" || ")
  return (
    head +
    guard +
    `${run}
rc=$?
${count}${why}
if ${gone}; then
  ${remove}
fi
exit $rc
`
  )
}

/**
 * The cmd wrapper a Windows Entry's task executes (CRLF — it is a Windows file). `installedAt`
 * (epoch seconds) is the install stamp an expiry counts from. Composes by the lifetime's
 * features, exactly as {@link shWrapper} does.
 */
export function cmdWrapper(entry: Pick<Entry, "id" | "dir" | "until">, cli: string[], installedAt: number): string {
  const { id, dir, until } = entry
  const log = file(dir, id, "\\", ".log")
  const q = (s: string) => `"${s}"`
  const argv = (sub: string[]) => [...cli, ...sub].map(q).join(" ")
  const run = `${argv(["run"])} >> ${q(log)} 2>&1`
  const remove = `${argv(["cron", "remove", id])} >> ${q(log)} 2>&1`
  const head = [
    "@echo off",
    "rem generated by loop.js -- `loop cron add`; regenerated on add, deleted on remove.",
    "rem Scheduled tasks get the user's registry environment: system- and user-level variables",
    "rem are present, profile-only ones are not -- set API keys at the user or system level.",
    `cd /d ${q(dir)} || exit /b 1`,
  ]
  const guard =
    until.expires === undefined
      ? []
      : [
          `rem Expires ${until.expires} after install. The cap bounds cost, so a tick past the deadline`,
          "rem removes the Entry instead of running. cmd parses the whole block before running it, so the",
          "rem exit survives the remove deleting this file. A failed clock leaves NOW at 0: degrade toward",
          "rem running, never toward a wrong removal.",
          "set NOW=0",
          `for /f %%t in ('powershell -NoProfile -Command "[DateTimeOffset]::UtcNow.ToUnixTimeSeconds()"') do set NOW=%%t`,
          `if %NOW% GEQ ${installedAt + durationSeconds(until.expires)} (`,
          `  ${remove}`,
          "  exit /b 0",
          ")",
        ]
  if (!until.settled && until.maxRuns === undefined) return [...head, ...guard, run, ""].join("\r\n")
  const runs = q(runsPath(dir, id, "cmd"))
  const count =
    until.maxRuns === undefined
      ? []
      : ["set RUNS=0", `if exist ${runs} set /p RUNS=<${runs}`, "set /a RUNS+=1", `>${runs} echo %RUNS%`]
  const why = until.settled
    ? [
        `rem 0 = settled ok, 2 = settled give-up (the MVP exit table) -- or run ${until.maxRuns}, the cap: this`,
        "rem Entry's job is done -- it removes itself. The remove deletes this file too, so it stays the",
        "rem last line that matters.",
      ]
    : [
        `rem Run ${until.maxRuns} is the cap: this Entry ends here. A settled exit alone never removes a`,
        "rem forever Entry -- each tick re-judges through the Verify gate; the cap is its only self-removal.",
        "rem The remove deletes this file too, so it stays the last line that matters.",
      ]
  const gone = [
    ...(until.settled ? [`if %RC%==0 ${remove}`, `if %RC%==2 ${remove}`] : []),
    ...(until.maxRuns === undefined ? [] : [`if %RUNS% GEQ ${until.maxRuns} ${remove}`]),
  ]
  return [...head, ...guard, run, "set RC=%ERRORLEVEL%", ...count, ...why, ...gone, "exit /b %RC%", ""].join("\r\n")
}

/** The impure boundary: an Entry's generated files on disk. Backends never touch the filesystem directly. */
export type WrapperFiles = {
  /** Write the wrapper at `path` (creating `.loop/cron/`), executable (0755) on unix. */
  write(path: string, text: string): void
  /** Delete a generated file (wrapper, run count) at `path`; one already gone is the goal state.
   *  The log is never touched. */
  remove(path: string): void
}

export function systemWrapperFiles(): WrapperFiles {
  return {
    write(path, text) {
      mkdirSync(dirname(path), { recursive: true })
      writeFileSync(path, text, "utf8")
      chmodSync(path, 0o755) // explicit: writeFileSync's mode option is clipped by the umask
    },
    remove(path) {
      rmSync(path, { force: true })
    },
  }
}

/**
 * The install {@link Step} every local Entry starts with: the wrapper lands before the scheduler
 * entry, so a fired Entry never points at a missing script, and a failed install takes it back
 * off disk.
 */
export function wrapperStep(files: WrapperFiles, path: string, text: string): Step {
  return {
    do: () => files.write(path, text),
    undo: () => files.remove(path),
  }
}
