import { describe, expect, test } from "bun:test"
import { resolve } from "node:path"
import { cmdWrapper, currentCli, runsPath, shWrapper, wrapperPath } from "./wrapper.ts"

// A fixed install stamp (epoch seconds); with the default expires=24h the deadline is +86400.
const AT = 1_700_000_000

describe("wrapperPath / runsPath", () => {
  test("an Entry's generated files live at <dir>/.loop/cron/<id>, in the flavor's own separators", () => {
    expect(wrapperPath("/home/me/proj", "abc123", "sh")).toBe("/home/me/proj/.loop/cron/abc123.sh")
    expect(wrapperPath("C:\\proj", "abc123", "cmd")).toBe("C:\\proj\\.loop\\cron\\abc123.cmd")
    expect(runsPath("/home/me/proj", "abc123", "sh")).toBe("/home/me/proj/.loop/cron/abc123.runs")
    expect(runsPath("C:\\proj", "abc123", "cmd")).toBe("C:\\proj\\.loop\\cron\\abc123.runs")
  })
})

describe("currentCli", () => {
  test("reruns the same bin: absolute runtime + CLI script", () => {
    expect(currentCli()).toEqual([process.execPath, resolve(process.argv[1]!)])
  })
})

describe("shWrapper (pure)", () => {
  const text = shWrapper({ id: "abc123", dir: "/home/me/proj", until: { settled: false } }, ["/bun", "/cli.ts"], AT)

  test("a login-shell shebang resolves PATH and API keys by reference at fire time", () => {
    expect(text.startsWith("#!/bin/bash -l\n")).toBe(true)
  })

  test("stands alone: cds into the project dir before anything runs", () => {
    expect(text).toContain("cd '/home/me/proj'")
  })

  test("forever: execs the absolute `loop run`, appending both streams to the Entry's log", () => {
    expect(text).toContain("exec '/bun' '/cli.ts' 'run' >> '/home/me/proj/.loop/cron/abc123.log' 2>&1")
  })

  test("says it is generated, and by what", () => {
    expect(text).toContain("generated by loop.js")
  })

  test("a dir with a single quote is escaped for the shell", () => {
    const t = shWrapper({ id: "x1", dir: "/o'brien/proj", until: { settled: false } }, ["/bun"], AT)
    expect(t).toContain("cd '/o'\\''brien/proj'")
    expect(t).toContain(">> '/o'\\''brien/proj/.loop/cron/x1.log'")
  })

  describe("until: settled — settle, the max-runs cap, the expiry", () => {
    const settled = shWrapper(
      { id: "abc123", dir: "/home/me/proj", until: { settled: true, maxRuns: 3, expires: "24h" } },
      ["/bun", "/cli.ts"],
      AT,
    )
    const remove = "'/bun' '/cli.ts' 'cron' 'remove' 'abc123' >> '/home/me/proj/.loop/cron/abc123.log' 2>&1"

    test("runs `loop run` as a child (no exec) so the exit code is inspectable", () => {
      expect(settled).toContain("'/bun' '/cli.ts' 'run' >> '/home/me/proj/.loop/cron/abc123.log' 2>&1")
      expect(settled).not.toContain("exec ")
    })

    test("a tick past the deadline — install + expires — removes the Entry instead of running", () => {
      expect(settled).toContain(`if [ "$(date +%s)" -ge ${AT + 86400} ]; then`)
      const expired = settled.slice(0, settled.indexOf("'run'"))
      expect(expired).toContain(remove)
      expect(expired).toContain("exit 0")
    })

    test("--expires resizes the expiry, in any unit", () => {
      const week = shWrapper({ id: "abc123", dir: "/home/me/proj", until: { settled: true, maxRuns: 3, expires: "7d" } }, ["/bun"], AT)
      expect(week).toContain(`-ge ${AT + 7 * 86400}`)
      const minutes = shWrapper({ id: "abc123", dir: "/home/me/proj", until: { settled: true, maxRuns: 3, expires: "90m" } }, ["/bun"], AT)
      expect(minutes).toContain(`-ge ${AT + 5400}`)
    })

    test("counts its runs in the Entry's .runs file, beside the wrapper", () => {
      expect(settled).toContain("runs=$(( $(cat '/home/me/proj/.loop/cron/abc123.runs' 2>/dev/null || echo 0) + 1 ))")
      expect(settled).toContain(`echo "$runs" > '/home/me/proj/.loop/cron/abc123.runs'`)
    })

    test("a settled exit — 0 (ok) or 2 (give-up) — or the max-runs-th run removes the Entry, last", () => {
      expect(settled).toContain(`if [ $rc -eq 0 ] || [ $rc -eq 2 ] || [ "$runs" -ge 3 ]; then`)
      expect(settled.lastIndexOf(remove)).toBeGreaterThan(settled.indexOf("'run'"))
    })

    test("any other exit before a cap is an interruption: `loop run`'s code is the wrapper's", () => {
      expect(settled).toContain("exit $rc")
    })
  })
})

describe("shWrapper — until: forever with opt-in caps: a cap ends it, a settle never does", () => {
  const capped = shWrapper(
    { id: "abc123", dir: "/home/me/proj", until: { settled: false, maxRuns: 10, expires: "7d" } },
    ["/bun", "/cli.ts"],
    AT,
  )

  test("carries the expiry guard and counts runs like a settled lifetime", () => {
    expect(capped).toContain(`if [ "$(date +%s)" -ge ${AT + 7 * 86400} ]; then`)
    expect(capped).toContain("runs=$(( $(cat '/home/me/proj/.loop/cron/abc123.runs'")
  })

  test("removes only at the run cap — a settled exit does not remove a forever Entry", () => {
    expect(capped).toContain(`if [ "$runs" -ge 10 ]; then`)
    expect(capped).not.toContain("$rc -eq 0")
    expect(capped).not.toContain("$rc -eq 2")
  })

  test("expires-only: guards the deadline, then execs — no run counting", () => {
    const t = shWrapper(
      { id: "abc123", dir: "/home/me/proj", until: { settled: false, expires: "7d" } },
      ["/bun", "/cli.ts"],
      AT,
    )
    expect(t).toContain(`if [ "$(date +%s)" -ge ${AT + 7 * 86400} ]; then`)
    expect(t).toContain("exec '/bun' '/cli.ts' 'run'")
    expect(t).not.toContain(".runs")
  })

  test("cmd flavor mirrors: run cap without the settled-exit removes", () => {
    const t = cmdWrapper(
      { id: "abc123", dir: "C:\\a b\\proj", until: { settled: false, maxRuns: 10 } },
      ["C:\\bun.exe", "C:\\cli.ts"],
      AT,
    )
    expect(t).toContain("if %RUNS% GEQ 10 ")
    expect(t).not.toContain("if %RC%==0 ")
    expect(t).not.toContain("GEQ " + String(AT)) // no expiry opted in — no deadline check
  })
})

describe("cmdWrapper (pure)", () => {
  const text = cmdWrapper({ id: "abc123", dir: "C:\\a b\\proj", until: { settled: false } }, ["C:\\bun.exe", "C:\\cli.ts"], AT)

  test("is a quiet batch file with CRLF line endings", () => {
    expect(text.startsWith("@echo off\r\n")).toBe(true)
    expect(text).not.toMatch(/[^\r]\n/) // every newline is CRLF — it is a Windows file
  })

  test("stands alone: cds (drive included) into the project dir, exiting if the dir is gone", () => {
    expect(text).toContain('cd /d "C:\\a b\\proj" || exit /b 1')
  })

  test("forever: runs the quoted `loop run`, appending both streams to the Entry's log", () => {
    expect(text).toContain('"C:\\bun.exe" "C:\\cli.ts" "run" >> "C:\\a b\\proj\\.loop\\cron\\abc123.log" 2>&1')
  })

  test("teaches where env must come from: the registry, not a profile", () => {
    expect(text).toContain("registry environment")
  })

  describe("until: settled — settle, the max-runs cap, the expiry", () => {
    const settled = cmdWrapper(
      { id: "abc123", dir: "C:\\a b\\proj", until: { settled: true, maxRuns: 3, expires: "24h" } },
      ["C:\\bun.exe", "C:\\cli.ts"],
      AT,
    )
    const remove = '"C:\\bun.exe" "C:\\cli.ts" "cron" "remove" "abc123" >> "C:\\a b\\proj\\.loop\\cron\\abc123.log" 2>&1'

    test("keeps CRLF endings", () => {
      expect(settled).not.toMatch(/[^\r]\n/)
    })

    test("a tick past the deadline removes the Entry instead of running; a missing clock runs on", () => {
      expect(settled).toContain("set NOW=0")
      expect(settled).toContain("[DateTimeOffset]::UtcNow.ToUnixTimeSeconds()")
      expect(settled).toContain(`if %NOW% GEQ ${AT + 86400} (`)
      const expired = settled.slice(0, settled.indexOf('"run"'))
      expect(expired).toContain(remove)
      expect(expired).toContain("exit /b 0")
    })

    test("counts its runs in the Entry's .runs file, beside the wrapper", () => {
      expect(settled).toContain('if exist "C:\\a b\\proj\\.loop\\cron\\abc123.runs" set /p RUNS=<"C:\\a b\\proj\\.loop\\cron\\abc123.runs"')
      expect(settled).toContain("set /a RUNS+=1")
      expect(settled).toContain('>"C:\\a b\\proj\\.loop\\cron\\abc123.runs" echo %RUNS%')
    })

    test("a settled exit — 0 (ok) or 2 (give-up) — or the max-runs-th run removes the Entry, last", () => {
      expect(settled).toContain(`if %RC%==0 ${remove}`)
      expect(settled).toContain(`if %RC%==2 ${remove}`)
      expect(settled).toContain(`if %RUNS% GEQ 3 ${remove}`)
    })

    test("any other exit before a cap is an interruption: `loop run`'s code is the task's", () => {
      expect(settled).toContain("exit /b %RC%")
    })
  })
})
